CO-2959 Account move fiscal year migration v11
CompassionCH/compassion-accounting pull request #102
Opened 2020-01-16 09:59 UTC by quentingigon

Not yet tested, as I had no data to do it

2020-01-24 13:34 UTC, ecino commented
Migration of sbc_compassion is done, you can finish this.

2020-01-27 09:59 UTC, quentingigon commented
The option is at the right place in the settings. I did not test the functionality because of a lack of data

2020-02-25 15:03 UTC, ecino requested changes

2020-02-25 15:03 UTC, ecino commented on account_move_fiscalyear/__manifest__.py
> +                'child_compassion',
Remove this dependency. We should not make it depedent of this module

2020-02-25 15:03 UTC, ecino commented on account_move_fiscalyear/views/res_config_bills_view.xml
> +            <field name="inherit_id" ref="child_compassion.compassion_settings"/>
Don't make this settings inherit from the settings of child_compassion. It's an accounting settings that should be placed in the accounting settings accordingly.

2020-02-28 14:33 UTC, ecino approved these changes

2020-02-28 14:34 UTC, merged