CO-3051 add activity to recurring_contracts
CompassionCH/compassion-accounting pull request #103
Opened 2020-02-18 13:28 UTC by josueBulle

related:
https://github.com/CompassionCH/compassion-modules/pull/1293
https://github.com/CompassionCH/compassion-switzerland/pull/1016

2020-02-24 16:40 UTC, ecino commented
Can you add OCA repository for mis_builder module so that travis goes green please?

2020-02-25 10:13 UTC, ecino requested changes

2020-02-25 10:13 UTC, ecino commented on mis_builder_spn_event_info/__manifest__.py
> +    'installable': True,
This should not be present in this PR

2020-02-25 10:20 UTC, ecino commented
After reflextion, can you move modules mis_builder* into compassion-switzerland repository ? It makes more sense there I think.

2020-02-25 12:12 UTC, ecino requested changes
I think you removed the class inheritance by mistake.

2020-02-25 12:19 UTC, josueBulle commented
The model `recurring_contract` was already inheriting `mail.activity.mixin` I just needed

2020-02-25 15:04 UTC, ecino approved these changes

2020-02-25 15:04 UTC, merged