L10n ch import camt054 mig v12
CompassionCH/compassion-accounting pull request #109
Opened 2020-05-12 13:56 UTC by quentingigon

To test this, I run the cron manually with this value: model.camt054_reconcile("1098",)
Previously, I had to reconstruct some data in my v12 database, as values for _acct_svcr_ref_ were lost during a migration. For that I used those psql commands:

- `CREATE TEMP TABLE tmp_lines (id int, acct_svcr_ref text);`
- `COPY tmp_lines FROM '/home/qgigon/account_move_lines_10.csv' (FORMAT csv);`
- `UPDATE account_move_line SET acct_svcr_ref = tmp_lines.acct_svcr_ref FROM tmp_lines WHERE account_move_line.id = tmp_lines.id;`
- `DROP TABLE tmp_lines;`

The CSV file used was created with pgadmin from a v10 database and contained _id_ +  _acct_svcr_ref_ for all rows with _acct_svcr_ref_ != ''

2020-05-12 14:06 UTC, quentingigon commented
Travis fails because it doesn't find the module _account_bank_statement_import_camt_details_ as it is in bank-statement-import

2020-05-15 07:01 UTC, ecino commented
You can add this line into `oca_dependenciest.txt`
```
bank-statement-import https://github.com/CompassionCH/bank-statement-import 12.0-camt-details
```

2020-05-15 07:04 UTC, ecino requested changes

2020-05-15 07:04 UTC, ecino commented on l10n_ch_import_camt054/__manifest__.py
> +        # 'account_payment_line_cancel',
You can remove completely

2020-05-15 07:04 UTC, ecino commented on l10n_ch_import_camt054/demo/test_data.yml
> +  !record {model: account.account, id: post_account, view: False}:super
`yaml` files are no more supported! You should replace it with `xml` file.

2020-05-15 07:21 UTC, ecino commented
Line 95 in custom parser won't be working (https://github.com/CompassionCH/compassion-accounting/blob/9f61c3f636aca78d900ec949d20c7a5853ed5e0a/l10n_ch_import_camt054/models/custom_parser.py#L95) as it uses the module `payment_line_cancel` which was removed and replaced by `account_payment_return`. You can take inspiration from module `l10n_ch_payment_return_sepa` which is importing files and doing as well the cancellation by creating a `account.payment.return` object : 
https://github.com/CompassionCH/l10n-switzerland/blob/12.0-everything-migrated/l10n_ch_payment_return_sepa/wizards/payment_return_import.py#L65
@davidwul Could you check that what I say is correct ?

2020-05-15 08:53 UTC, quentingigon commented
I am waiting for the confirmation from David that the proposed change is correct

2020-05-18 08:53 UTC, ecino commented
It looks like `Crypto` must be added in the requirements.txt

2020-05-18 09:31 UTC, quentingigon commented
Travis does not start

2020-05-19 11:43 UTC, ecino commented
Please fix the tests which are still failing.

2020-05-27 12:51 UTC, merged