T0103 invoice payment order restrictions.
CompassionCH/compassion-accounting pull request #188
Opened 2023-04-04 14:28 UTC by simgonzalez

Add restrictions for the payment on payment order.

2023-04-06 08:03 UTC, ecino requested changes

2023-04-06 08:03 UTC, ecino commented on recurring_contract/models/move.py
> +                continue
This could simply be included in the filtered conditions in the loop above.

2023-04-06 08:03 UTC, ecino commented on invoice_restrictions/models/account_move.py
> +        if self.mapped('payment_order_id').filtered(lambda p: p.state not in ["draft", "open"]):
Should we filter for specific vals change only? Wouldn't some changes without impact on the payment order still be possible? I feel this global way is too preventive and might raise errors for cases that are not problematic in the end.

2023-04-06 08:03 UTC, ecino commented on invoice_restrictions/__manifest__.py
> +#    @author: Cyril Sester <csester@compassion.ch>, Emanuel Cino
It's not really reflecting the reality.

2023-04-06 10:37 UTC, simgonzalez commented
The rules must be rethought because it's not as easy as it looks and we have to define rules for exceptional case. Like taking out of the payment order the move and changing his payment_state from not paid to paid. and ...

2023-04-06 13:54 UTC, simgonzalez commented on invoice_restrictions/models/account_move.py
> +            payment_line_ids = move_to_modify.mapped('line_ids.payment_line_ids')
test the status in vals.

2023-04-17 11:06 UTC, ecino approved these changes

2023-04-17 11:07 UTC, merged